"""add phone_number to user table

Revision ID: 03055a88086e
Revises: f6ad6ea1036e
Create Date: 2023-06-30 16:37:09.788249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03055a88086e'
down_revision = 'f6ad6ea1036e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
